name: "nfl"
version: "1.0.0"
config-version: 2

profile: "nfl"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  staging:
    +materialized: view
    +schema: staging
  core:
    dimensions:
      +schema: core
      +materialized: table
    facts:
      +schema: core
      +materialized: table
  marts:
    +schema: insights
    +materialized: view


