version: 2

models:
  - name: stg_nfl_salaries_2024
    description: "Staging model for NFL player salaries in 2024 season."
    columns:
      - name: PLAYER_NAME
        tests:
          - not_null
      - name: TEAM
        tests:
          - not_null
      - name: SALARY
        tests:
          - not_null