version: 2

sources:
  - name: web_scraping
    database: NFL_DATA_LAB
    schema: RAW_NFL
    tables:
      - name: SALARIES_2024
        description: "Salaries of NFL players for the 2024 season, scraped from Spotrac."
        columns:
          - name: NAME
            description: "Player's full name."
          - name: TEAM
            description: "Abbreviated team name."
          - name: SALARY
            description: "Player's annual salary in US dollars."
            tests:
              - not_null